sitemap:
  changefreq: weekly
module:
  mounts:
    - source: assets
      target: assets
    - source: layouts
      target: layouts
  imports:
    - path: github.com/Saydemr/wowchemy-hugo-themes/modules/wowchemy-core
